### ISSUE TITLE
Problems with the 'e' test

### ISSUE THREAD

**Issue by flalini** [charMstr/printf_lover_v2#2]
The content of this article may be strange because it uses a translator.

There is a problem with 'e' not working properly.
The **utils/generated_tests/sources/main_call_test_funcs.c** file appears to be a problem.
Look at the conditions in line 85 at **!my_ft_strncmp(argv[1], "n", 3)** .
Changing "n" to "e" makes it possible to test.

**Comment by charMstr** [comment]
Issue fixed by Kohyounghwan
 Thanks for pointing it out in the first place
